create database EL4U;
use EL4U;

CREATE TABLE test(
    ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1024) NOT NULL,
    LINK_MP3 VARCHAR(1024),
    CREATE_DATE datetime,
	UPDATE_DATE datetime,
    CREATE_BY VARCHAR(50),
	UPDATE_BY VARCHAR(50),
    ANSER_TEST text
);
create table group_question(
	ID int(10) not null primary key auto_increment,
    ID_TEST int(10),
    LINK_IMG varchar(256),
    LINK_MP3 varchar(256),
	CONTENT text
);

create table question(
	ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_TEST INT(11),
    LINK_MP3 VARCHAR(1024),
	LINK_IMG VARCHAR(1024),
    QUESTION VARCHAR(1024),
	ANSWER_A VARCHAR(1024),
    ANSWER_B VARCHAR(1024),
    ANSWER_C VARCHAR(1024),
    ANSWER_D VARCHAR(1024),
    CORRECT_ANSWER VARCHAR(1),
    QUESTION_ORDER int,
    FOREIGN KEY (ID_TEST) REFERENCES test(id)
);
create table user(
	ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(256),
	PASSWORD VARCHAR(256),
	LINK_IMG VARCHAR(1024),
    PHONE_NUMBER VARCHAR(1024),
	EMAIL VARCHAR(1024),
    RULE VARCHAR(1024),
    STATUST VARCHAR(1024),
    DELETED VARCHAR(1024),
	CREATE_DATE datetime,
     CREATE_BY VARCHAR(50)
);
create table thongke(
	ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_USER INT(11),
	ID_TEST INT(11),
    CORRECT_ANSWER INT,
    WRONG_ANSWER INT,
	CREATE_DATE datetime,
    READING INT,
	LISTENING INT
);
